const MOVIES_TYPES = {
  RESET_STATE: "RESET_STATE",

  GET_ALL_MOVIES_BEGIN: "GET_ALL_MOVIES_BEGIN",
  GET_ALL_MOVIES_SUCCESS: "GET_ALL_MOVIES_SUCCESS",
  GET_ALL_MOVIES_FAILURE: "GET_ALL_MOVIES_FAILURE",

  GET_MOVIES_BY_ID_BEGIN: "GET_MOVIES_BY_ID_BEGIN",
  GET_MOVIES_BY_ID_SUCCESS: "GET_MOVIES_BY_ID_SUCCESS",
  GET_MOVIES_BY_ID_FAILURE: "GET_MOVIES_BY_ID_FAILURE",
};

export default MOVIES_TYPES;
